version: '3.8'
services:
  api-db:
    env_file:
      - ./services/web/.env
    image: postgres:alpine
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
    volumes:
      - ./services/db:/app/db
    restart: always
  api-pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=godzilliqa@godz.io
      - PGADMIN_DEFAULT_PASSWORD=godzilliqa
    ports:
      - "5050:80"
    depends_on:
      - api-db
  api-redis:
    image: "redis:alpine"
  api-web:
    environment:
      - DATABASE_URL=postgresql+asyncpg://local:local@api-db:5432/test_db
    build:
      context: './services/web/'
      dockerfile: Dockerfile
    volumes:
      - ./services/web:/app/web
    env_file:
      - ./services/web/.env
    ports:
      - "8080:8080"
      - "5678:5678"
    depends_on:
      - api-db
      - api-redis
    restart: always
  api-bot:
    environment: 
      - PORT=8443
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://local:local@api-db:5432/test_db
    build:
      context: './services/bot/'
      dockerfile: Dockerfile
    volumes:
      - ./services/bot:/app/bot
    env_file:
      - ./services/bot/.env
    ports:
      - "8443:8443"
      - "5679:5678"
    depends_on:
      - api-db
      - api-redis
    restart: always
