"""New fields for chat model

Revision ID: 09fa9bee9e38
Revises: 72f0cad66d03
Create Date: 2021-05-15 00:05:17.758238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09fa9bee9e38"
down_revision = "72f0cad66d03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chatmodel", sa.Column("chat_name", sa.String(), nullable=False))
    op.add_column("chatmodel", sa.Column("deleted", sa.Boolean(), nullable=False))
    op.alter_column("chatmodel", "chat_id", existing_type=sa.NUMERIC(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chatmodel", "chat_id", existing_type=sa.NUMERIC(), nullable=True)
    op.drop_column("chatmodel", "deleted")
    op.drop_column("chatmodel", "chat_name")
    # ### end Alembic commands ###
