"""more chat info

Revision ID: 540d6fc0b093
Revises: 09fa9bee9e38
Create Date: 2021-05-15 16:06:14.441737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "540d6fc0b093"
down_revision = "09fa9bee9e38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chatmodel", sa.Column("creator", sa.String(), nullable=False))
    op.add_column("chatmodel", sa.Column("inviter", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatmodel", "inviter")
    op.drop_column("chatmodel", "creator")
    # ### end Alembic commands ###
