"""removed_roles

Revision ID: bec0dda6be5e
Revises: c37f72ccdfd1
Create Date: 2021-06-16 18:10:31.638118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bec0dda6be5e"
down_revision = "c37f72ccdfd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    op.drop_column("user", "scopes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
