"""scopes

Revision ID: c37f72ccdfd1
Revises: 04c396cd67c5
Create Date: 2021-06-16 16:51:05.346092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37f72ccdfd1'
down_revision = '04c396cd67c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'scopes')
    # ### end Alembic commands ###
