"""chat reporting

Revision ID: cfc7bd55b1a2
Revises: 540d6fc0b093
Create Date: 2021-05-15 20:56:23.869822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfc7bd55b1a2"
down_revision = "540d6fc0b093"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chatmodel", sa.Column("report_channel", sa.NUMERIC(), nullable=True))
    op.add_column(
        "chatmodel", sa.Column("toggle_report_command", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chatmodel", "toggle_report_command")
    op.drop_column("chatmodel", "report_channel")
    # ### end Alembic commands ###
