"""Initial

Revision ID: d26502703bfa
Revises: 
Create Date: 2021-05-12 14:55:29.388173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d26502703bfa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
