"""User Roles

Revision ID: f82722a89a12
Revises: 61d5038b178a
Create Date: 2021-06-14 22:28:29.340780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f82722a89a12"
down_revision = "61d5038b178a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("role", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
